from fastapi import APIRouter
import json
from datetime import datetime
import random

router = APIRouter(prefix="/track-e", tags=["Track E"])

@router.get("/dataset/mock")
async def get_mock_dataset():
    """
    Returns mock data for a 'Bar Chart Race' visualization.
    Scenario: Programming Language Popularity (2000-2023)
    Structure: Series-based (compatible with ECharts standard dataset)
    """
    timeline = [str(year) for year in range(2000, 2024)]
    categories = ["Python", "JavaScript", "Java", "C++", "C#", "PHP", "Go", "Rust"]
    
    # Initialize current values
    current_values = {lang: random.randint(100, 500) for lang in categories}
    
    # Initialize series structure: { "Python": [val2000, val2001...], ... }
    series_map = {lang: [] for lang in categories}
    
    for year in timeline:
        # Simulate growth/decline for each language in this year
        for lang in categories:
            # Random growth factor logic
            if lang == "Python":
                # Python starts slow, booms after 2012 (AI/Data era)
                if int(year) < 2012:
                    growth = random.uniform(1.05, 1.15)
                else:
                    growth = random.uniform(1.15, 1.35)
            elif lang == "JavaScript":
                # Consistent steady growth (Web era)
                growth = random.uniform(1.1, 1.25)
            elif lang == "Rust":
                # Only exists/popular later
                if int(year) < 2015:
                    growth = 1.0 # Flat or 0 ideally, but let's keep it simple
                    current_values[lang] = max(current_values[lang], 10) # Keep low
                else:
                    growth = random.uniform(1.3, 1.5) # Boom
            elif lang == "Go":
                 if int(year) < 2010:
                    current_values[lang] = max(current_values[lang], 20)
                    growth = 1.0
                 else:
                    growth = random.uniform(1.2, 1.4)
            elif lang == "PHP":
                # Early boom, then stagnation/decline relative to others
                if int(year) < 2010:
                    growth = random.uniform(1.1, 1.2)
                else:
                    growth = random.uniform(0.95, 1.05)
            elif lang == "Java":
                # Steady enterprise giant
                growth = random.uniform(1.05, 1.15)
            else:
                # C++, C#
                growth = random.uniform(1.0, 1.15)
                
            # Apply growth
            current_values[lang] = int(current_values[lang] * growth)
            
            # Append to series
            series_map[lang].append(current_values[lang])

    # Convert to list format expected by frontend: [{name: "Python", data: [...]}, ...]
    series_list = [
        {"name": lang, "data": series_map[lang]}
        for lang in categories
    ]

    return {
        "meta": {
            "title": "Programming Language Popularity Evolution",
            "subTitle": "Mock Data generated by FineSTEM Backend",
            "source": "Simulation Engine",
            "updateTime": datetime.utcnow().isoformat()
        },
        "timeline": timeline,
        "categories": categories,
        "series": series_list
    }
