export type ColorMode = 'neon' | 'classic';

export interface SimulationConfig {
  configId?: string; // Generated by system
  gravity: number; // 0.0 ~ 2.0, default 1.0
  frictionAir: number; // 0.0 ~ 0.1, default 0.005
  length1: number; // 50 ~ 400, default 150
  length2: number; // 50 ~ 400, default 100
  mass1: number; // 1 ~ 50, default 20
  mass2: number; // 1 ~ 50, default 15
  initialAngle1: number; // 0 ~ 2PI, default PI/2
  initialAngle2: number; // 0 ~ 2PI, default PI/2
  trailLength: number; // 0 ~ 1000, default 200
  colorMode: ColorMode; // default 'neon'
}

export const DEFAULT_CONFIG: SimulationConfig = {
  gravity: 1.0,
  frictionAir: 0.005,
  length1: 150,
  length2: 100,
  mass1: 20,
  mass2: 15,
  initialAngle1: Math.PI / 2,
  initialAngle2: Math.PI / 2,
  trailLength: 200,
  colorMode: 'neon',
};
